-- University Table
CREATE TABLE UNIVERSITIES 
(
    UNIVERSITY_ID NUMBER(10),
    UNIVERSITY_NAME VARCHAR2(50),
    UNIVERSITY_LOC VARCHAR2(50),
    UNIVERSITY_Image_Link VARCHAR2(300),
    PRIMARY KEY (UNIVERSITY_ID)
);

--drop table UNIVERSITIES;

--Department Table
CREATE TABLE DEPARTMENTS(
    DEPT_ID NUMBER(10),
    DEPT_NAME VARCHAR2(50),
    DEPT_DESC VARCHAR2(200),
    UNIV_ID NUMBER(10),
    PRIMARY KEY (DEPT_ID),
    FOREIGN KEY (UNIV_ID) REFERENCES UNIVERSITIES(UNIVERSITY_ID)
);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT univ_id_fk
   FOREIGN KEY (UNIV_ID)
   REFERENCES UNIVERSITIES(UNIVERSITY_ID);
--drop table departments

--USERS table
CREATE TABLE USERS
(
    USER_ID NUMBER(10),
    PASSWORD VARCHAR2(100),
    USER_ROLE VARCHAR2(20),
    INSERT_DATE DATE,
    NAME VARCHAR2(50),
    PRIMARY KEY (USER_ID)
);
--drop table users


--COURSE TABLE
CREATE TABLE COURSES
(
COURSE_ID NUMBER(10),
COURSE_NAME VARCHAR2(50),
COURSE_DESC VARCHAR2(200),
PRIMARY KEY (COURSE_ID)
);
-- drop table courses;

--PROFESSOR TABLE
CREATE TABLE PROFESSORS
(
    PROF_ID NUMBER(10),
    PROF_NAME VARCHAR2(50),
    COURSE_ID NUMBER(10),
    DEPT_ID  NUMBER(10),
    PRIMARY KEY (PROF_ID, COURSE_ID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);
--drop table PROFESSORS

create SEQUENCE student_seq START WITH 1 increment by 1;

-- STUDENT TABLE
CREATE TABLE STUDENTS
(
    ID NUMBER(10) NOT NULL,
    STUDENT_ID NUMBER(10) NOT NULL,
    STUDENT_NAME VARCHAR2(50) NOT NULL,
    COURSE_ID NUMBER(10) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);

--drop table STUDENTS

-- GRADES TABLE
CREATE TABLE GRADES
(   
    GRADE_ID NUMBER(10),    
    GRADE VARCHAR2(3),
    FOREIGN KEY (GRADE_ID) REFERENCES STUDENTS(ID)
);
--drop table grades
